language: csharp
solution: ServForOracle.NetCore
dist: trusty
mono: none
dotnet: 2.1.4
addons:
  sonarcloud:
    organization: "roysanchez-github"
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ServForOracle.NetCore.UnitTests/ServForOracle.NetCore.UnitTests.csproj
  - sonar-scanner